id: P000714
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-16 16:38:31.476616
source_metadata:
  id: bdr:W1KG5468
  title: རས་ཆུང་རྡོ་རྗེ་གྲགས་པའི་རྣམ་ཐར་རིས་སུ་བྲིས་པ་ལྷ་ཡི་ཆར་
  author: ''
  volumes:
    12f0e1c8316a4de49c29aeba723738fe:
      image_group_id: I1KG5475
      title: ''
      volume_number: 1
      total_pages: 176
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
