id: I58907BBF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T23:04:09+00:00'
last_modified: '2022-06-07T12:44:04.083914+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5468
  title: རས་ཆུང་རྡོ་རྗེ་གྲགས་པའི་རྣམ་ཐར་རིས་སུ་བྲིས་པ་ལྷ་ཡི་ཆར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B8CF:
      image_group_id: I1KG5475
      title: ''
      total_pages: 176
      order: 1
      base_file: B8CF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
